
POST http://localhost:4200/api/users/register HTTP/1.1
Content-Type: application/json

{
  "username": "demo4",
  "password": "demo4"
}

###

POST http://localhost:4200/api/users/login HTTP/1.1
Content-Type: application/json

{
  "username": "demo6",
  "password": "demo6"
}

###

GET http://localhost:4200/api/users/4 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlbW80IiwiaWF0IjoxNTgzMzY4NjQwLCJleHAiOjE1ODMzNjg3MDB9.RDvZKFbmkIBAjD6Q1dab1D-VeNw3ZsVOYVvVNidIcTM

###

POST http://localhost:4200/api/users HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlbW80IiwiaWF0IjoxNTgzMzc1MjY5LCJleHAiOjE1ODMzNzUzMjl9.APYiocwlRH7xLOjFgicYWRNroZFHlpRodCNgknC2k9M

{
  "username": "demo6",
  "password": "demo6"
}